services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - mongo
  redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - mongo-store:/data/db

volumes:
  mongo-store:
  redis:
